---
title: "Syllabus"
description: |
  Duke University, Spring 2024
---

## Teaching Team

[Eric Green](https://globalhealth.duke.edu/people/green-eric), PhD

This course will introduce you to research designs and methods in global health. Global health is a multi-disciplinary field, so we will consider approaches common to the behavioral and social sciences, public health, and medicine.

Our primary interest will be the study of causal inference. In global health, we are often interested in knowing what treatments, programs, interventions, and policies "work" and why. To answer questions of impact, we often turn to randomized controlled trials, a mainstay of medical research. As such, we will spend time exploring the rationale, process, and limitations of experiments.

Randomization is not always possible or advisable, however, and researchers must build a causal argument using non-experimental methods. We will review several approaches, consider relevant threats to causal inference, and discuss how to improve non-experimental research designs.

Along the way, we will cover research basics, such as asking evidence-based research questions, searching the literature, developing a theory of change, identifying indicators and collecting data, selecting research participants, and testing hypotheses. In the latter part of the course, we will turn to more specialized topics in global health research, such as writing research proposals and manuscripts, economic analyses, and making an impact.

## Course Goals and Learning Objectives

We have two broad goals this semester:

1. to make you a better consumer of research; and
2. to help you design your first study.

The course is divided into five modules:

1. Get started with global health research
2. Consider threats to validity
3. Select a research design
4. Specify your methods
5. Practice good science and make an impact

By the end of the semester, you should be able to:

* Describe the landscape of global health research
* Begin developing research ideas
* Effectively search the literature and make use of systematic reviews and meta-analyses
* Critically appraise scientific work 
* Ask a good research question and develop study aims and hypotheses 
* Develop a theory of change and logic model
* Identify indicators to measure throughout the causal chain
* Understand the fundamental challenge of causal inference and strategies for building a causal argument
* Articulate the benefits and limitations of random assignment
* Explain the logic and limitations of different quasi-experimental and observational designs that can be used when randomization is not possible or ethical
* Select the best method of data collection given study objectives and resources
* Devise a sampling strategy to meet study objectives and resources
* Design a high-powered study
* Describe common challenges when building research collaborations and articulate strategies for being a good collaborator
* Understand the process of ethical review
* Explain the benefits of open science practices to colleagues
* Understand how scientists share their work by publishing and giving talks at conferences
* Make a plan to promote the use of research in policymaking

## Class Format

Class sessions will typically begin with a brief lecture designed to reinforce or extend pre-class learning, but the aim is to spend most of the class time on application activities. Activities will be based on assigned readings and will sometimes incorporate the use of tools like R/RStudio. Please review the activity before class, just as you might prepare for a lab in biology or chemistry.

## Resources

Readings, videos, and podcasts will be assigned and provided.

## Workload

A reasonable rule of thumb is somewhere between 2:1 and 3:1 out-of-class to in-class hours. At the upper end, this is about 100 hours of outside class time this semester.

## Evaluation

Your final grade will be a weighted average of several components: application activities, homework, module quizzes, and a study proposal.

**Application activities**: Short activities designed to be completed during class in groups of 2-3. Pass/fail.

**Homework**: Assignments generally due one week after the end of the module.

**Module Quizzes**: At the conclusion of modules 1-4, we will have a class session where we spend 25 minutes reviewing the material, followed by a 30 minute quiz. In the final 20 minutes of the session we will review the answers.

**Study proposal**: Your study proposal will take the place of the final exam. Details on format and process will be provided.

| Component                             | Weight |
|:----                                  |:--:    |
| In-class application activities       | 20%    |
| Homework                              | 20%    |
| Quizzes                               | 25%    |
| Study proposal                        | 35%    |

Ranges for letter grades will be set at the end of the semester, and grades may be curved. Cumulative scores of at least 90, 80, and 70 will be guaranteed at least an A-, B-, and C-, respectively. Please do not ask me to round up your grade.  

## Policies

Please note the following:

* There will be no make-ups for missed **application activities** because we will often review the answers in session and post the answers ASAP. We will excuse up to 4 missed activities for any reason (meaning you do not need to contact us to explain). 
* **Homework** will be due at the start of class on the date indicated on the schedule. Late submissions will be accepted until we share the model answers (could be as soon as later the same day). Late submissions may be penalized. 
* If you miss 1 of the 4 **module quizzes**, your score on this component will be the average of the 4 remaining quizzes. If you miss more than 1 quiz we may require a dean's excuse to avoid assigning a score of 0. There will be no make-ups. 
* Students should abide by the [Duke Community Standard](https://studentaffairs.duke.edu/conduct/about-us/duke-community-standard){target="_blank"} at all times. If a questionable circumstance arises, do not hesitate to seek my guidance (before is always better than after). Take steps to [avoid plagiarism](http://library.duke.edu/research/plagiarism){target="_blank"} in your work.

## Equity and Inclusion at DGHI

In 2020 DGHI formed the Equity Task Force to identify and address structural inequities related to global power dynamics, race, ethnicity, gender, and all marginalized identities throughout the institute. See [here](https://globalhealth.duke.edu/about/diversity-equity-and-inclusion){target="_blank"} for more information on this work.

If you require any accommodations or arrangements (hearing, vision, English language comprehension, extenuating personal or family circumstances, etc.) please let me know ASAP and, if relevant, please contact the Student Disability Access Office (SDOA) to ensure the accommodation/arrangements can be implemented in a timely fashion.
