project:
  type: website
  output-dir: docs

website:
  title: "Global Health Research"
  navbar:
    background: '#1f9ac9'
    left:
    - text: "GLHLTH 371 / PSY 309"
      href: 371.html
    - text: "GLHLTH 702"
      href: 702.html
    - text: "Schedule"
      href: schedule.html
    - text: "Modules"
      menu:
        - text: "Module 1"
          href: mod1.html
        - text: "Module 2"
          href: mod2.html
        - text: "Module 3"
          href: mod3.html


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



