---
title: "Module 1"
---

## Get Started

By the end of this module, you should be able to:

* Describe the landscape of global health research
* Begin developing research ideas
* Effectively search the literature and make use of systematic reviews and meta-analyses
* Critically appraise scientific work 

## 1.2: Global health research

Research is defined as a systematic investigation whose goal is to develop or contribute to generalizable knowledge. As global health is the study and practice of improving health and achieving equity in health, global health research research includes all systematic efforts to create generalizable knowledge of how we can improve health and achieve equity in health for everyone, everywhere.

Given the complexity of our global health challenges, global health research is multidisciplinary and interdisciplinary. This means that, as a budding global health researcher, you will likely collaborate on teams with colleagues from many different fields. Each discipline has its own methodological preferences and core approaches, but we all operate in the same research landscape that is divided into basic and applied research. Much of the literature in global health focuses on our applied challenges, so you will read a lot about clinical research and trials, translational research, implementation research, and M&E (monitoring and evaluation).

So no matter what discipline you call home, or what stage of research you find most interesting, you can make great contributions to our collective efforts to improve health and achieve equity in health.

### Learning Objectives

* Understand the definition of global health and what distinguishes global health from other related fields
* Explain what makes research scientific
* Describe the landscape of global health research
* Enumerate the phases of clinical trials
* Describe the key actors in the funding and production of global health research/initiatives
* List several scholarly journals that publish global health research

### Prepare

* Read [Revised GHR Chapter 1 (use this specific link)](https://ericpgreen.github.io/ghr_ebook/ghr.html){target="_blank"}.
* Read ["Fighting glioblastoma with recombinant poliovirus"](https://medium.com/@ericpgreen/fighting-glioblastoma-with-recombinant-poliovirus-5bef1ebc7f41)
* Think about where your interests lie in the global health research landscape and be prepared to share with classmates.
* Browse one or more of the journals that publish global health research and find at least one article that interests you.

### During Class

* [Deck](https://drive.google.com/file/d/1P854E-xk4qjNQy3WOUdV4lA-4Q-rhrmX/view?usp=share_link)
* [Activity](https://docs.google.com/document/d/1iKT2ymNkiAd5ny8Cb6qMgOpU0nysRDn4pA9DR5tpQ20/edit?usp=sharing)

In this activity you will consider where your interests lie in the global health research landscape and identify academic journals that publish work related to these interests.



## 1.3: Build collaborations / Develop questions

Research ideas take time to develop. You can jumpstart the process by learning about interesting work. Attend talks, watch webinars, meet with mentors, talk with fellow students. Above all else, read the literature. When you are just starting out, try skimming widely read journals to get a sense of current developments in global health disciplines. Follow interesting leads by noting article keywords, inspecting reference lists, and seeking out clues authors leave you in the introduction and discussion.

### Learning Objectives

* Appreciate the process for developing research ideas and identifying potential research problems
* Identify research goals
* Ask good research questions
* Develop testable hypotheses

### Prepare

* Read [Revised GHR Chapter 2 (use this specific link)](https://ericpgreen.github.io/ghr_ebook/collaborations.html){target="_blank"}.
* TBD (link is not working)

### During Class

* [Deck](https://drive.google.com/file/d/1ayhclTHzAFfBXg7KFSTwXU1YeJd7qgJ-/view?usp=share_link)
* [Activity](https://docs.google.com/document/d/1tP5X-d1nsKQLHXSS1BgcrSUD__NKrjKPAI3lSyM71o8/edit?usp=sharing)

## 1.4: Search the literature / Read scientific articles

Throughout the process of identifying research problems, framing research questions, and designing your study, you'll return over and over to the literature to ensure that your study is informed by prior work and is poised to contribute to your field. In this session you'll learn strategies for searching the literature effectively and managing what you find.

Critical appraisal is an important part of the scientific process. It’s what we do when asked to review a manuscript prior to publication, evaluate a grant proposal, read a new paper published in our field, and prepare a systematic review or meta-analysis. You might feel unprepared to provide critical feedback on someone else’s work until you know more about research methods, designs, and analysis, but it’s easy to get started if you use a framework like the reporting guidelines published by the Equator Network or some of the tools listed below in additional resources. When it’s time to communicate your feedback, be nice. Be critical, be honest about the flaws you perceive, but always be nice and assume that the authors did their best. If their best is not publishable and cannot be fixed with revision, then recommend that the paper be rejected or the grant not funded. It happens. Even in rejecting someone’s work you can offer ideas for improvement.

### Learning Objectives

* Conduct an effective literature search
* Understand options for accessing journal articles
* Use a reference manager
* Understand how to read and critique a systematic review 
* Interpret a meta-analysis and forest plot
* Critically appraise scientific work
* Outline the anatomy of a scientific paper
* Deliver constructive feedback

### Prepare

* TBD (link is not working)
* Review [article skimming template](https://drive.google.com/open?id=1y5X_-368KZtesT78Ic6A0PIF-4MxoSqFHNxF_fSjwNA)

### During Class

* [Activity](https://docs.google.com/document/d/1dpwoN7Cowj5PeNCcEs94AdjlWCzbnj206BJ6Cn1eRys/edit?usp=sharing)

During class we will participate in a workshop led by Duke librarians that will teach you how to construct a research question, design and implement a search strategy, import the results into Zotero, and automatically compile and format bibliographies in a word processor.


## Homework

| Assignment                    | Due Date |
|:------------------------------|:---------|
| [Module 1 homework](https://docs.google.com/document/d/154DIqlStBf_mQcZEK7ZbtFe7sDgAluu_XgNiKzhzxbM/edit?usp=sharing){target="_blank"}            | Sept 21      |
