---
title: "Module 2"
---

## Consider Threats to Validity

By the end of this module, you should be able to:

* Explain the main approaches to statistical inference and threats to statistical conclusion validity
* Understand the fundamental challenge of causal inference, common causal inference methods, and threats to internal validity
* Articulate why generalizability matters and the threats to external validity
* Describe the importance of study measurement and ways to establish construct validity

## 2.1 and 2.2: Statistical inference and statistical conclusion validity

### Prepare

* Read [GHR statistical inference](https://ericpgreen.github.io/ghr_ebook/statinference.html){target="_blank"}.
* Read [Resnick (2019)](https://www.vox.com/latest-news/2019/3/22/18275913/statistical-significance-p-values-explained){target="_blank"}
* Read [Modern Dive, Chapter 9 (sections 9.1 and 9.2)](https://moderndive.com/9-hypothesis-testing.html#nhst-conclusion){target="_blank"}

### During Class

* [Activity 1](https://docs.google.com/document/d/1beOhGCdEdwXHM6l1T8KDmnIPOm84vAQ8oEOxgbnH8g4/edit?usp=sharing){target="_blank"}
* [Deck](https://drive.google.com/file/d/1QwgUMqNcU56PmwSXARDdr-0euefgBvQm/view?usp=drive_link){target="_blank"}
* Activity 2: On Posit Cloud

## 2.3 and 2.4: Causal inference and internal validity

### Prepare

* Read [GHR causal inference](https://ericpgreen.github.io/ghr_ebook/causalinference.html){target="_blank"}.

### During Class

* [Deck with activities](activities/2.3_causal-inference.html){target="_blank"}

## 2.5: Measurement and construct validation

### Prepare

* Read [GHR measurement](https://ericpgreen.github.io/ghr_ebook/construct.html){target="_blank"}.

### During Class

* [Activity 1](https://docs.google.com/document/d/1My6M1S2tDFW9XPtXNtSes-Fv7ACtVlRcLSqArUWlIXA/edit?usp=sharing){target="_blank"}
* [Activity 2](https://docs.google.com/document/d/1IQRcc2gUqoIFOB1ikrofQnDIqG7TNY3YOX6_bzvxM30/edit?usp=sharing){target="_blank"}
* [Deck](https://drive.google.com/file/d/13URJWguj-Zbsnvqp-A5iJIxlH3L5Z20q/view?usp=drive_link){target="_blank"}

## 2.6: Generalizability and external validity

### Prepare

* Read Shadish, Cook, and Campbell (2002), [Chapter 3](https://moodle2.units.it/pluginfile.php/132646/mod_resource/content/1/Estratto_ShadishCookCampbellExperimental2002.pdf){target="_blank"}.

### During Class

* [Activity](https://docs.google.com/document/d/1dQj4-GvdXqNN0ANUPVbf2UPrkJWSheMVWKt4pJUjgBY/edit?usp=sharing){target="_blank"}
* [Deck](https://drive.google.com/file/d/1B5m90w-R6bGBsxCHjKANyRHbrfF7_0oC/view?usp=sharing){target="_blank"}




## Homework

| Assignment                    | Due Date |
|:------------------------------|:---------|
| [Module 2 homework](https://docs.google.com/document/d/1DV30QSgUJCVVAIO488k5Ckl5CseCWV_zexasF9T9x4s/edit?usp=sharing){target="_blank"}            | Oct 22      |

