---
title: "Module 4"
---

## Specify the Methods

By the end of this module, you should be able to:

* Identify your target population and create a sampling plan
* Determine how many participants to invite
* Select the best method of data collection given study objectives and resources

## 4.1: Sampling

### Prepare

* Read Sections 1.3 and 1.4 of [OpenIntro Statistics](https://www.openintro.org/redirect.php?go=os4_tablet&referrer=/stat/os4.php){target="_blank"}
* Watch [this video on sampling from the DHS](https://youtu.be/DD5npelwh80){target="_blank"}
* Read the chapter on Power in *Running Randomized Evaluations* (Box)

### During Class

* [Deck](https://drive.google.com/file/d/1m1gS02bcE70CIU7O18-lpPo2eAZH-4jJ/view?usp=share_link)
* Activity

## 4.2: Power and Sample Size

### Prepare

* Chapter 6 "Statistical Power" in Glennerster, R. & Takavarasha, K. (2013). Running Randomized Evaluations: A Practical Guide (Box)
* [Chapter 8 "Sample Size Justification"](https://lakens.github.io/statistical_inferences/power.html) in Lakens, D. (2022). Improving Your Statistical Inferences. https://doi.org/10.5281/zenodo.6409077

### During Class

* [Deck](https://drive.google.com/file/d/1m1gS02bcE70CIU7O18-lpPo2eAZH-4jJ/view?usp=share_link)

## 4.3: Data Collection

### Prepare

* [JPAL Survey Design](https://www.povertyactionlab.org/resource/survey-design)
* Chapter 5 "Outcomes and Instruments" in Glennerster, R. & Takavarasha, K. (2013). Running Randomized Evaluations: A Practical Guide (Box)
* FHI360 [Qualitative Research Methods Field Guide](https://www.fhi360.org/resource/qualitative-research-methods-data-collectors-field-guide) (read Module 1, skim Modules 2-4)
* Haberland, N. A., Kelly, C. A., Mulenga, D. M., Mensch, B. S., & Hewett, P. C. (2016). Women’s perceptions and misperceptions of male circumcision: a mixed methods study in Zambia. [*PloS one, 11(3), e0149517*](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0149517).

### During Class

* [Deck](https://drive.google.com/file/d/13byszG_4R2yhYG8xVczDeGYNr1IXv15V/view?usp=share_link)
* [Deck](https://drive.google.com/file/d/1h29_4gxk7AlYDZsfx1AOACxID7bNdW5m/view?usp=share_link)
* Activity: Interviewing

## Homework

| Assignment                    | Due Date |
|:------------------------------|:---------|
| [Module 4 homework](https://docs.google.com/document/d/1QL3fNAflkj74Cs-RKew4Xk2s-jNIzThgoDHs50nmD0U/edit?usp=sharing){target="_blank"}            | Nov 30      |


