---
title: "Schedule"
description: |
  Fall 2024
---

| Week | Date | Module | Session |
|- | --- | --- | ---- |
| 1 | Aug 27 | - | 1.1 Welcome |
| 2 | Aug 29 | 1. Get started | [1.2 Global health research](mod1.html#global-health-research) |
| 2 | Sept 3 | 1. Get started | [1.3 Build collaborations / Develop research ideas and questions](mod1.html#build-collaborations-develop-questions) |
| 3 | Sept 5 | 1. Get started | [1.4 Search the literature / Read scientific articles](mod1.html#search-the-literature-read-scientific-articles) |
| 3 | Sept 10 | 1. Get started | 1.5 Review/Assess |
| 4 | Sept 12 | 2. Consider threats to validity | [2.1 Statistical inference and statistical conclusion validity](mod2.html#and-2.2-statistical-inference-and-statistical-conclusion-validity) |
| 4 | Sept 17 | 2. Consider threats to validity | [2.2 Statistical inference and statistical conclusion validity](mod2.html#and-2.2-statistical-inference-and-statistical-conclusion-validity) |
| 5 | Sept 19 | 2. Consider threats to validity | [2.3 Causal inference and internal validity](mod2.html#and-2.4-causal-inference-and-internal-validity) |
| 5 | Sept 24 | 2. Consider threats to validity | [2.4 Causal inference and internal validity](mod2.html#and-2.4-causal-inference-and-internal-validity) |
| 6 | Sept 26 | 2. Consider threats to validity | [2.5 Measurement and construct validity](mod2.html#and-2.6-measurement-and-construct-validation) |
| 6 | Oct 1 | 2. Consider threats to validity | [2.6 Measurement and construct validity](mod2.html#and-2.6-measurement-and-construct-validation) |
| 7 | Oct 3 | 2. Consider threats to validity | [2.7 Generalizability and external validity](mod2.html#generalizability-and-external-validity) |
| 7 | Oct 8 | 2. Consider threats to validity | 2.8 Review/Assess |
| 8 | Oct 10 | 3. Select a research design | [3.1 Experimental](mod3.html#and-3.2-experimental) |
| 8 | Oct 17 | 3. Select a research design | [3.2 Experimental](mod3.html#and-3.2-experimental) |
| 9 | Oct 22 | 3. Select a research design | 3.3 [Quasi-experimental](mod3.html#quasi-experimental) |
| 9 | Oct 24 | 3. Select a research design | [3.4 Quasi-experimental](mod3.html#quasi-experimental) |
| 10 | Oct 29 | 3. Select a research design | 3.5 Confounder-control |
| 10 | Oct 31 | 3. Select a research design | 3.6 Descriptive |
| 11 | Nov 5 | 3. Select a research design | 3.7 Review/Assess |
| 11 | Nov 7 | No class | No class |
| 12 | Nov 12 | 4. Specify the methods | [4.1 Sampling / 4.2 Sample size](mod4.html#sampling) |
| 12 | Nov 14 | 4. Specify the methods | [4.3 Data collection](mod4.html#data-collection) |
| 13 | Nov 19 | 4. Specify the methods | 4.4 Review/Assess |
| 13 | Nov 21 | 5. Practice good science | 5.1 All the things |
| 14 | Nov 26 | 5. Practice good science | 5.2 Writing workshop (371/309) / Peer review session (702) |
| 14 | Dec 3 | 5. Practice good science | 5.3 Peer review session (371/309) |
| 15 | Dec 5 | 5. Practice good science | 5.4 Writing workshop (371/309) |

<!--
| 14 | Apr 16 | 5. Practice good science | 5.2 Peer review / Writing workshop (371) |
| 14 | Apr 18 | 5. Practice good science | 5.3 Peer review session (371 only) |
| 15 | Apr 23 | 5. Practice good science | 5.4 Writing workshop (371 only) |
-->
